apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: your_backend_image:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://username:password@db:5432/document_management"
            - name: S3_BUCKET_NAME
              value: "your_s3_bucket"
            - name: AWS_ACCESS_KEY_ID
              value: "your_access_key"
            - name: AWS_SECRET_ACCESS_KEY
              value: "your_secret_key"
